config/routes.rb
Rails.application.routes.draw do
  root 'exchanges#index'
  resources :exchanges do
    collection do
      post 'reload'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
require 'csv'
class Exchange < ApplicationRecord

  REQUIRED_ATTR = %w[name last_price percent_change high24hr low24hr sell_orders buy_orders count_in_btc].freeze

  enum ex_type: %i[BTC_BCN BTC_BELA BTC_BLK BTC_BTCD BTC_BTM BTC_BTS BTC_BURST BTC_CLAM BTC_DASH BTC_DGB BTC_DOGE
                    BTC_EMC2 BTC_FLDC BTC_FLO BTC_GAME BTC_GRC BTC_HUC BTC_LTC BTC_MAID BTC_OMNI BTC_NAUT BTC_NAV
                    BTC_NEOS BTC_NMC BTC_NOTE BTC_NXT BTC_PINK BTC_POT BTC_PPC BTC_RIC BTC_SJCX BTC_STR BTC_SYS BTC_VIA
                    BTC_XVC BTC_VRC BTC_VTC BTC_XBC BTC_XCP BTC_XEM BTC_XMR BTC_XPM BTC_XRP BTC_ETH BTC_SC BTC_BCY
                    BTC_EXP BTC_FCT BTC_RADS BTC_AMP BTC_DCR BTC_LSK BTC_LBC BTC_STEEM BTC_SBD BTC_ETC BTC_REP BTC_ARDR
                    BTC_ZEC BTC_STRAT BTC_NXC BTC_PASC BTC_GNT BTC_GNO USDT_BTC BTC_BCH]
  # enum ex_type: %i[BTC_BCN BTC_BELA BTC_BLK BTC_BTCD BTC_BTM
  #                   BTC_NEOS BTC_NMC BTC_NOTE BTC_NXT BTC_PINK
  #                    BTC_POT BTC_PPC BTC_RIC BTC_SJCX BTC_STR
  #                 BTC_SYS BTC_BTS USDT_BTC]

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << REQUIRED_ATTR
      order(:name).each do |p|
        csv << [p.name, p.last_price, p.percent_change, p.high24hr, p.low24hr, (p.sell_orders.to_f).round, (p.buy_orders.to_f).round, (p.count_in_btc.to_f).round]
      end
    end
  end
end

app/models/plnx.rb
require 'httparty'
require 'json'
require 'watir'
require 'nokogiri'
require 'benchmark'
class Plnx

  API_URL = 'https://poloniex.com/public?command=returnTicker'
  WEB_URL = 'https://poloniex.com/exchange#'

  def initialize
    @data = load_data
  end

  def load_data
    response = HTTParty.get(API_URL)
    data = JSON.parse(response.body)
    data.delete_if {|key, value| Exchange.ex_types.keys.exclude? key}
  end

  def create_exchanges
    @data.each do |key, value|
      web_url = WEB_URL + key

      begin
        @client = Selenium::WebDriver::Remote::Http::Default.new
        @client.timeout = 50
        browser = Watir::Browser.new(:phantomjs, :http_client => @client)
        sleep 1
        browser.goto(web_url)


        sleep 1

        document = Nokogiri::HTML(browser.html)
        while document.css('#asksTotal').text.empty?
          sleep 1
          p "add 1 sec to parse' pair #{key}"
          document = Nokogiri::HTML(browser.html)
        end
        browser.close
        Exchange.create(ex_type: key,
                        name: key.gsub('BTC_', ''),
                        last_price: value['last'],
                        percent_change: (((value['percentChange']).to_f)*100).round(2),
                        high24hr: value['high24hr'],
                        low24hr: value['low24hr'],
                        sell_orders: document.css('#asksTotal').text,
                        buy_orders: document.css('#bidsTotal').text,
                        count_in_btc: 1.00/((value['last']).to_f))
      rescue Timeout::Error
        puts "Timeout Rescue"
        browser.close
        retry
      end

    end
  end

  def self.start
    time = Benchmark.measure do
      Plnx.new.create_exchanges
    end
    $time_load = time.real
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  include ActionController::MimeResponds
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: 'poloniex', password: 'bitcoin'

  # GET /exchanges
  # GET /exchanges.json
  def index
    @exchanges = Exchange.order(:name)
    respond_to do |format|
      format.html
      format.csv { send_data @exchanges.to_csv }
    end
  end

  def reload
    Exchange.delete_all
    Plnx.start
    Exchange.find_by_ex_type(:USDT_BTC).update_column(:name, ' BTC')
    redirect_to action: :index
  end

  # GET /exchanges/1
  # GET /exchanges/1.json
  def show
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges
  # POST /exchanges.json
  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to @exchange, notice: 'Exchange was successfully created.' }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1
  # PATCH/PUT /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to @exchange, notice: 'Exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1
  # DELETE /exchanges/1.json
  def destroy
    @exchange.destroy
    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: 'Exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exchange_params
      params.require(:exchange).permit(:ex_type, :last_price, :lowest_ask, :highest_bid, :percent_change, :base_volume, :quote_volume, :high24hr, :low24hr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<%= form_with(model: exchange, local: true) do |form| %>
  <% if exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ex_type %>
    <%= form.number_field :ex_type, id: :exchange_ex_type %>
  </div>

  <div class="field">
    <%= form.label :last_price %>
    <%= form.text_field :last_price, id: :exchange_last_price %>
  </div>

  <div class="field">
    <%= form.label :lowest_ask %>
    <%= form.text_field :lowest_ask, id: :exchange_lowest_ask %>
  </div>

  <div class="field">
    <%= form.label :highest_bid %>
    <%= form.text_field :highest_bid, id: :exchange_highest_bid %>
  </div>

  <div class="field">
    <%= form.label :percent_change %>
    <%= form.text_field :percent_change, id: :exchange_percent_change %>
  </div>

  <div class="field">
    <%= form.label :base_volume %>
    <%= form.text_field :base_volume, id: :exchange_base_volume %>
  </div>

  <div class="field">
    <%= form.label :quote_volume %>
    <%= form.text_field :quote_volume, id: :exchange_quote_volume %>
  </div>

  <div class="field">
    <%= form.label :high24hr %>
    <%= form.text_field :high24hr, id: :exchange_high24hr %>
  </div>

  <div class="field">
    <%= form.label :low24hr %>
    <%= form.text_field :low24hr, id: :exchange_low24hr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exchanges</h1>
last update <%= @exchanges.last.try(:created_at) %> - <%= $time_load.try(:round) %> sec.
<h2><%= link_to 'Download', exchanges_path(format: 'csv') %></h2>

<%= form_tag(reload_exchanges_path) do %>
    <h2>    <%= submit_tag "Load New Data" %> </h2>
<% end %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Last price</th>
    <th>Percent change</th>
    <th>High24hr</th>
    <th>Low24hr</th>
    <th>Sell orders</th>
    <th>Buy orders</th>
    <th>Count in BTC</th>
  </tr>
  </thead>

  <tbody>
  <% @exchanges.each do |exchange| %>
      <tr class="<%= cycle('even', 'odd') -%>">
        <td><%= exchange.name %></td>
        <td><%= exchange.last_price %></td>
        <td class="<%= exchange.percent_change.to_f > 0 ? 'green' : 'red' %>"><%= exchange.percent_change %></td>
        <td><%= exchange.high24hr %></td>
        <td><%= exchange.low24hr %></td>
        <td><%= exchange.sell_orders %></td>
        <td><%= exchange.buy_orders %></td>
        <td><%= exchange.count_in_btc %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/exchanges/new.html.erb
<h1>New Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Back', exchanges_path %>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ex type:</strong>
  <%= @exchange.ex_type %>
</p>

<p>
  <strong>Last price:</strong>
  <%= @exchange.last_price %>
</p>

<p>
  <strong>Lowest ask:</strong>
  <%= @exchange.lowest_ask %>
</p>

<p>
  <strong>Highest bid:</strong>
  <%= @exchange.highest_bid %>
</p>

<p>
  <strong>Percent change:</strong>
  <%= @exchange.percent_change %>
</p>

<p>
  <strong>Base volume:</strong>
  <%= @exchange.base_volume %>
</p>

<p>
  <strong>Quote volume:</strong>
  <%= @exchange.quote_volume %>
</p>

<p>
  <strong>High24hr:</strong>
  <%= @exchange.high24hr %>
</p>

<p>
  <strong>Low24hr:</strong>
  <%= @exchange.low24hr %>
</p>

<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoloniexBot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>